### ISSUE TITLE
PCM 16 bit

### ISSUE THREAD

**Issue by oq-x** [gopxl/beep#160]
how can i play []int16 pcm data?

**Comment by MarkKremer** [comment]
I'm kind of surprised we don't have a first-party function for that. But, you can take some inspiration from the `dataStreamer` in the internal package to write your own pcm data streamer: https://github.com/gopxl/beep/blob/2c3b789a7aad7c2f25dd71d157a2099537b266a4/internal/testtools/streamers.go#L19

You'll need to convert the int16 data to floats between -1 and 1. So divide by `1 << 15` = 32768 if I'm correct.

**Comment by oq-x** [comment]
var w webm.WebM
	reader, err := webm.Parse(bytes.NewReader(data), &w)
	if err != nil {
		return nil, beep.Format{}, err
	}

	audioTrack := w.FindFirstAudioTrack()
	form := beep.Format{
		SampleRate:  beep.SampleRate(audioTrack.SamplingFrequency),
		NumChannels: int(audioTrack.Channels),
		Precision:   2,
	}

	decoder, err := gopus.NewDecoder(int(audioTrack.SamplingFrequency), int(audioTrack.Channels))
	if err != nil {
		return nil, beep.Format{}, err
	}

	var frameSizeMs = 60.0
	var frameSize = float64(audioTrack.Channels) * frameSizeMs * audioTrack.SamplingFrequency / 1000

	return beep.StreamerFunc(func(samples [][2]float64) (n int, ok bool) {
		frame := <-reader.Chan

		pcm, err := decoder.Decode(frame.Data, int(frameSize), false)
		if err != nil {
			return 0, false
		}
		for i := range samples {
			samples[i][0] = float64(int(pcm[i] / 1 << 15))
		}
		return len(samples), true
	}), form, err
	
	i tried like this and it doesnt work

**Comment by MarkKremer** [comment]
Convert your samples to float first and then divide. Otherwise you'l get an int in the range of -1 to 1 and that doesn't contain a lot of information.

Samples has 2 channels. The code only fills the first one. If you're getting sound in only one ear, then that's why.

Thirdly, the `samples` slice will be of a certain size which is determined by the calling code (speaker?). This size probably doesn't match the size of the frames. So you'll need to keep track of where in the frame you're to fill `samples` and only request a new frame when you're done with the previous one.

I'm unfamiliar with the decoder library you're using, but given that it's a wrapper around a C library, I think the framesize passed to `decoder.Decode` must be the size of the frame data passed as the first argument. I may be wrong but please check the intended usage.

If it still doesn't work afterwards, I would like to know in what way it doesn't work. No sound? Cracking noises, panic/error etc.?

**Comment by oq-x** [comment]
I got it working now will post code later 
Supports seeking too

**Comment by oq-x** [comment]
This is the final implementation:
var ErrAlreadyClosed = errors.New("already closed")

type pcmStreamer struct {
    pcm       []int16
    pcmIdx    int
    frameSize int

    decoder *gopus.Decoder
    packets <-chan webm.Packet
    reader  *webm.Reader

    duration time.Duration

    pos int

    err error

    closed bool
}

var _ beep.StreamSeekCloser = (*pcmStreamer)(nil)

func (s *pcmStreamer) Err() error {
    err := s.err
    s.err = nil
    return err
}

func (s *pcmStreamer) Seek(n int) error {
    s.reader.Seek(SampleRate.D(n))
    s.pos = n
    s.pcm = nil
    s.pcmIdx = 0
    return nil
}

func (s *pcmStreamer) Position() int {
    return s.pos
}

func (s *pcmStreamer) Len() int {
    return SampleRate.N(s.duration)
}

func (s *pcmStreamer) Close() error {
    if s.closed {
        return ErrAlreadyClosed
    }
    s.closed = true
    return nil
}

func (s *pcmStreamer) Stream(samples [][2]float64) (n int, ok bool) {
    if s.closed {
        s.err = ErrAlreadyClosed
        return
    }
    if s.pos >= SampleRate.N(s.duration) {
        s.err = io.EOF
        return 0, false
    }
    for n < len(samples) {
        if s.pcmIdx >= len(s.pcm) {
            select {
            case packet := <-s.packets:
                s.pcm, s.err = s.decoder.Decode(packet.Data, int(s.frameSize), false)
                s.pcmIdx = 0
            default:
            }
        }
        if len(s.pcm) <= s.pcmIdx || s.err != nil {
            //audio done
            break
        }
        for ; n < len(samples); n++ {
            left := float64(s.pcm[s.pcmIdx]) / 32767
            right := float64(s.pcm[s.pcmIdx+1]) / 32767
            samples[n][0] = left
            samples[n][1] = right
            s.pcmIdx += 2
            if s.pcmIdx >= len(s.pcm) {
                break
            }
        }
    }

    s.pos += len(samples)

    return n, true
}
